name: Generate Signal Reports

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت (در ساعت‌های 0, 6, 12, 18 به وقت UTC)
  workflow_dispatch:  # امکان اجرای دستی

jobs:
  generate-report:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      # کلون کردن مخزن
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب پایتون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ایجاد پوشه data
      - name: Create data directory
        run: mkdir -p data

      # اجرای اسکریپت تولید گزارش
      - name: Generate report
        run: python src/signal_tracker.py --report

      # آپلود فایل گزارش به‌عنوان artifact
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: signal-report
          path: data/signals_report_*.xlsx
          retention-days: 7  # فایل‌ها به مدت 7 روز نگه داشته می‌شوند
