name: Generate Signal Reports

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create data directory
        run: mkdir -p data

      - name: Generate report
        run: python src/signal_tracker.py --report
        continue-on-error: true  # ادامه حتی در صورت خطا

      - name: List files in data directory
        run: ls -l data/  # لاگ‌گیری برای تأیید تولید فایل

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: signal-report
          path: data/signals_report_*.xlsx
          retention-days: 7
        if: always()  # آپلود حتی در صورت خطا